(function(){
  window.CAP741_CHAPTER_DATA = [
    { chapter: '00', description: 'General' },
    { chapter: '01', description: 'Maintenance Policy' },
    { chapter: '02', description: 'Operations' },
    { chapter: '03', description: 'Support' },
    { chapter: '04', description: 'Airworthiness Limitations' },
    { chapter: '05', description: 'Time Limits / Maintenance Checks' },
    { chapter: '06', description: 'Dimensions and Areas' },
    { chapter: '07', description: 'Lifting and Shoring' },
    { chapter: '08', description: 'Leveling and Weighing' },
    { chapter: '09', description: 'Towing and Taxiing' },
    { chapter: '10', description: 'Parking, Mooring, Storage and Return To Service' },
    { chapter: '11', description: 'Placards and Markings' },
    { chapter: '12', description: 'Servicing' },
    { chapter: '13', description: 'Hardware and General Tools' },
    { chapter: '15', description: 'Aircrew Information' },
    { chapter: '16', description: 'Change of Role' },
    { chapter: '18', description: 'Vibration and Noise Analysis' },
    { chapter: '20', description: 'Standard Practices - Airframe' },
    { chapter: '21', description: 'Air Conditioning and Pressurization' },
    { chapter: '22', description: 'Auto Flight' },
    { chapter: '23', description: 'Communications' },
    { chapter: '24', description: 'Electrical Power' },
    { chapter: '25', description: 'Equipment / Furnishings' },
    { chapter: '26', description: 'Fire Protection' },
    { chapter: '27', description: 'Flight Controls' },
    { chapter: '28', description: 'Fuel' },
    { chapter: '29', description: 'Hydraulic Power' },
    { chapter: '30', description: 'Ice and Rain Protection' },
    { chapter: '31', description: 'Indicating / Recording Systems' },
    { chapter: '32', description: 'Landing Gear' },
    { chapter: '33', description: 'Lights' },
    { chapter: '34', description: 'Navigation' },
    { chapter: '35', description: 'Oxygen' },
    { chapter: '36', description: 'Pneumatic' },
    { chapter: '37', description: 'Vacuum' },
    { chapter: '38', description: 'Water / Waste' },
    { chapter: '39', description: 'Electrical - Electronic Panels and Multipurpose Components' },
    { chapter: '40', description: 'Multisystem' },
    { chapter: '41', description: 'Water Ballast' },
    { chapter: '42', description: 'Integrated Modular Avionics (IMA)' },
    { chapter: '43', description: 'Emergency Solar Panel System (ESPS)' },
    { chapter: '44', description: 'Cabin Systems' },
    { chapter: '45', description: 'Central Maintenance / Onboard Maintenance Systems' },
    { chapter: '46', description: 'Information Systems' },
    { chapter: '47', description: 'Nitrogen Generation / Inert Gas System' },
    { chapter: '48', description: 'In Flight Fuel Dispensing' },
    { chapter: '49', description: 'Airborne Auxiliary Power' },
    { chapter: '50', description: 'Cargo and Accessory Compartments' },
    { chapter: '51', description: 'Standard Practices and Structures - General' },
    { chapter: '52', description: 'Doors' },
    { chapter: '53', description: 'Fuselage' },
    { chapter: '54', description: 'Nacelles / Pylons' },
    { chapter: '55', description: 'Stabilizers' },
    { chapter: '56', description: 'Windows' },
    { chapter: '57', description: 'Wings' },
    { chapter: '60', description: 'Standard Practices - Prop./Rotor' },
    { chapter: '61', description: 'Propellers / Propulsion' },
    { chapter: '62', description: 'Main Rotor(s)' },
    { chapter: '63', description: 'Main Rotor Drive(s)' },
    { chapter: '64', description: 'Tail Rotor' },
    { chapter: '65', description: 'Tail Rotor Drive' },
    { chapter: '66', description: 'Folding Blades / Pylon' },
    { chapter: '67', description: 'Rotors Flight Control' },
    { chapter: '70', description: 'Standard Practices - Engine' },
    { chapter: '71', description: 'Power Plant' },
    { chapter: '72', description: 'Engine' },
    { chapter: '73', description: 'Engine - Fuel and Control' },
    { chapter: '74', description: 'Ignition' },
    { chapter: '75', description: 'Bleed Air' },
    { chapter: '76', description: 'Engine Controls' },
    { chapter: '77', description: 'Engine Indicating' },
    { chapter: '78', description: 'Exhaust' },
    { chapter: '79', description: 'Oil' },
    { chapter: '80', description: 'Starting' },
    { chapter: '81', description: 'Turbines (Reciprocating Engines)' },
    { chapter: '82', description: 'Water Injection' },
    { chapter: '83', description: 'Accessory Gear Box (Engine Driven)' },
    { chapter: '84', description: 'Propulsion Augmentation' },
    { chapter: '85', description: 'Reciprocating Engine' },
    { chapter: '91', description: 'Charts' },
    { chapter: '97', description: 'Image Recording' }
  ];
})();
