(function(){
  window.CAP741_CHAPTER_DATA = [
    { chapter: '01', description: 'General Description' },
    { chapter: '02', description: 'Ground Handling and Servicing' },
    { chapter: '03', description: 'Weight and Balance' },
    { chapter: '04', description: 'Airworthiness Limitations' },
    { chapter: '05', description: 'Time Limits/Maintenance Checks' },
    { chapter: '06', description: 'Dimensions and Areas' },
    { chapter: '07', description: 'Lifting and Shoring' },
    { chapter: '08', description: 'Leveling and Weighing' },
    { chapter: '09', description: 'Towing and Taxiing' },
    { chapter: '10', description: 'Parking and Mooring' },
    { chapter: '11', description: 'Placards and Markings' },
    { chapter: '12', description: 'Servicing - Airframe' },
    { chapter: '13', description: 'Servicing - Engines and APU' },
    { chapter: '14', description: 'External Lights' },
    { chapter: '15', description: 'Navigation Lights' },
    { chapter: '16', description: 'Doors' },
    { chapter: '17', description: 'Windows and Windshields' },
    { chapter: '18', description: 'Emergency Equipment' },
    { chapter: '19', description: 'Portable Equipment' },
    { chapter: '20', description: 'Standard Practices - Airframe' },
    { chapter: '21', description: 'Air Conditioning' },
    { chapter: '22', description: 'Autoflight' },
    { chapter: '23', description: 'Communications' },
    { chapter: '24', description: 'Electrical Power' },
    { chapter: '25', description: 'Equipment/Furnishings' },
    { chapter: '26', description: 'Fire Protection' },
    { chapter: '27', description: 'Flight Controls' },
    { chapter: '28', description: 'Fuel Storage' },
    { chapter: '29', description: 'Hydraulic Power' },
    { chapter: '30', description: 'Fuel Quantity Indicating' },
    { chapter: '31', description: 'Instruments' },
    { chapter: '32', description: 'Landing Gear' },
    { chapter: '33', description: 'Wheels and Brakes' },
    { chapter: '34', description: 'Landing Gear Doors' },
    { chapter: '35', description: 'Oxygen' },
    { chapter: '36', description: 'Pneumatics' },
    { chapter: '37', description: 'Pneumatic Controls' },
    { chapter: '38', description: 'Oxygen' },
    { chapter: '39', description: 'Pneumatic Power' },
    { chapter: '40', description: 'Water/Waste' },
    { chapter: '41', description: 'General Navigation' },
    { chapter: '42', description: 'Integrated Modular Avionics' },
    { chapter: '43', description: 'Airborne Maintenance Data' },
    { chapter: '44', description: 'Cabin Systems' },
    { chapter: '45', description: 'Cabin Compartments' },
    { chapter: '46', description: 'Cabin Systems - Safety' },
    { chapter: '47', description: 'Passenger Service Units' },
    { chapter: '48', description: 'Flight Compartment' },
    { chapter: '49', description: 'Anti-Icing and Deicing' },
    { chapter: '50', description: 'Auxiliary Power' },
    { chapter: '51', description: 'Structures' },
    { chapter: '52', description: 'Doors' },
    { chapter: '53', description: 'Fuselage' },
    { chapter: '54', description: 'Nacelles/Pylons' },
    { chapter: '55', description: 'Stabilizers' },
    { chapter: '56', description: 'Windows' },
    { chapter: '57', description: 'Wings' },
    { chapter: '58', description: 'Propellers/Rotors' },
    { chapter: '59', description: 'Propulsion' },
    { chapter: '60', description: 'Ignition' },
    { chapter: '61', description: 'Engine Controls' },
    { chapter: '62', description: 'Engine Indicating' },
    { chapter: '63', description: 'Engine Fuel and Control' },
    { chapter: '64', description: 'Engine Oil' },
    { chapter: '65', description: 'Engine Starting' },
    { chapter: '66', description: 'Engine Vibration' },
    { chapter: '67', description: 'Powerplant Controls' },
    { chapter: '68', description: 'Auxiliary Power Unit' },
    { chapter: '69', description: 'Ignition and Starting' },
    { chapter: '70', description: 'Engine Air' },
    { chapter: '71', description: 'Engine General' },
    { chapter: '72', description: 'Engine Controls' },
    { chapter: '73', description: 'Engine Fuel and Control' },
    { chapter: '74', description: 'Ignition' },
    { chapter: '75', description: 'Air Intake' },
    { chapter: '76', description: 'Engine Indicating' },
    { chapter: '77', description: 'Engine Oil' },
    { chapter: '78', description: 'Exhaust' }
  ];
})();
